#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
    entities:
      - App\Entity\Rating
      - App\Entity\Feature
      - App\Entity\Plan

    design:
      brand_color: '#009999'

    site_name: 'MercrediInventions'
